export const ArraybufferDataType = {
	COLOR_CMYK: "col_cmyk",
	COLOR_GPU: "col",
	COLOR_HSL: "col_hsl",
	COLOR_HSLA: "col_hsla",
	COLOR_HSV: "col_hsv",
	COLOR_HSVA: "col_hsva",
	COLOR_RGB: "col_rgb",
	COLOR_RGBA: "col_rgba",
	COLOR_RYB: "col_ryb",
	COLOR_RYBA: "col_ryba",
	COLOR_XYZ: "col_xyz",
	EULER: "euler",
	MATRIX2: "mat2",
	MATRIX3: "mat3",
	MATRIX4: "mat4",
	POLAR: "polar",
	QUATERNION: "qua",
	SPHERICAL: "spherical",
	VECTOR2: "vec2",
	VECTOR3: "vec3",
	VECTOR4: "vec4",
};
